In [4]:
from joblib import dump, load # We can Load our model with the help of JOblib Function in Sklearn
model = load('I&G Real Estate Pvt Ltd.joblib') 
import numpy as np

In [5]:
features = np.array([[-0.53942006,  3.12628155, -10.12165014, -5.27288841, -1.42262747,
       -4.241100041041, -1.31238772,  55.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])


model.predict(features)

array([21.348])

In [6]:
features = np.array([[-0.43942006,  5.12628155, -1.12165014, -0.27288841, -1.42262747,
        -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
        -0.97491834,  0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, -0.27288841, -1.0542567 ,
         0.49865392, -1.3938808 ,  7.19312325, -0.65766683, -0.78557904,
        -0.69277865,  0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, -0.27288841,  0.47919371,
         0.28660512,  0.87020968, -0.68730678,  1.63579367,  1.50571521,
         0.81196637,  0.44624347,  0.81480158],
       [-0.42292925, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         5.13494109, -0.52225911,  0.37882487, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.81939807],
       [-0.40786253, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         12.0450661 , -1.42222622,  0.79643404, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.91902752]])


model.predict(features)

array([22.476, 25.545, 16.461, 37.533, 37.507])

In [17]:
attributes = np.array([[-0.53942006,  4.12628155, -10.12165014, -5.27288841, -1.42262747,
       2.241100041041, -1.31238772,  55.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, 5.86091034]])

#attributes are the values of houses like no. of rooms etc 
model.predict(attributes)

array([30.307])

In [40]:
attributes = np.array ([[ -114, 22, 23, 25, -500, 36, 54, 268, -457, 54, 55, 25, 25],
                        [ 114, 22, 23, 25, -500, 36, 54, 268, -457, 54, 55, 25, 25],
                        [ 14, -22, 253, 25, -56, 36, 54, 268, -457, 54, 55, 25, 25],
                        [ -0.0056, 22, 63, 25, -500, 36, 54, 268, -457, 54, 55, 25, 25],
                        [ -11, 22, 23, 25, -500, -55, 54, 268, -457, 54, 55, 25, 25]
                        
                         
    
    
    
])
model.predict(attributes)

array([25.506, 23.221, 23.241, 23.668, 18.099])